apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ryan
  name: ryan
spec:
  replicas: 10
  selector:
    matchLabels:
      app: ryan
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: ryan
    spec:
      containers:
        - image: httpd:alpine3.19
          name: httpd

